### ISSUE TITLE
PMMP4.xへの対応

### ISSUE THREAD

**Issue by NekoFuwa1739** [aieuo/ReplenishResources#1]
以前とてもサーバーでお世話になっていたプラグインで、生活サーバーでの人工資源に不可欠な存在です。
4.x以降のサポートはしていただけないでしょうか?
![Screenshot_20220829-192351_Microsoft Remote Desktop](https://user-images.githubusercontent.com/62869023/187180633-55a66a64-70e5-405b-bb83-616f0332d20c.jpg)

**Comment by aieuo** [comment]
アップデートしました #2

**Comment by NekoFuwa1739** [comment]
ありがとうございます！
